config/routes.rb
Rails.application.routes.draw do
  get 'errors/internal_server_error'
  # get 'errors/not_found'
  # get 'users_rides/new'
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  # get 'users_rides/create'
  # get 'users_rides/edit'
  # get 'users_rides/update'
  # get 'users_rides/destroy'
  devise_for :users

  # raise ActionController::RoutingError.new('Not Found')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # resources :users  # do
  #   resources :rides, only: [:create, :new, :edit, :destroy, :update]
  #  end


  resources :rides, only: [:create, :new, :edit, :destroy, :update]  do
    resources :users_rides, only: [:new]
  end

  resources :users_rides, only: [:index, :create, :edit, :update, :destroy]

  resources :components, only: [:show, :create, :new, :edit, :destroy, :update]

  resources :bicycle_components
  resources :rides, only: [:show, :index]
  # resources :warranties
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/bicycle_rack", to: "bicycles#bicycle_rack", as: :bicycle_rack
  get "/new_bicycle_code", to: "bicycles#new_code", as: :new_code
  get "/new_bicycle_validation", to: "bicycles#new_code_validation", as: :new_code_validation
  get "/my_rides", to: "rides#my_rides", as: :my_rides
  resources :rides, only: [:index]

  resources :bicycles do
    resources :components, only: [:index]
    resources :maintenances, only: [:new, :create, :index, :update]
    resources :warranties, only: [:new, :create, :index, :update]
    resources :insurance_policies, only: [:new, :create, :index, :update]
  end

    resources :maintenances, only: [:destroy]
    resources :warranties, only: [:destroy]
    resources :insurance_policies, only: [:destroy]
  root to: "pages#home"
  end

  # Defines the root path route ("/")
  # root "posts#index

app/models/insurance_policy.rb
class InsurancePolicy < ApplicationRecord
  belongs_to :bicycle
  validates :insurer, :policy_number, presence: true
  validates :policy_number, presence: true
  validates :bicycle_id, presence: true
end

app/controllers/insurance_policies_controller.rb
# app/controllers/insurance_policies_controller.rb
class InsurancePoliciesController < ApplicationController
  before_action :set_insurance_policy, only: [:edit, :update, :destroy]
  before_action :set_bicycle, only: [:create, :edit, :update, :destroy]



  def index
    @bicycle = Bicycle.find(params[:bicycle_id])
    @insurance_policies = InsurancePolicy.where(bicycle_id:@bicycle.id)

  end

  def show
    @insurance_policy = InsurancePolicy.find(params[:id])
  end

  def new
    # @insurance_policy = InsurancePolicy.new
    @bicycle = Bicycle.find(params[:bicycle_id]) # Find the parent bicycle
    @insurance_policy = @bicycle.insurance_policies.build
  end

  def create
    @bicycle = Bicycle.find(params[:bicycle_id]) # Find the parent bicycle
    @insurance_policy = @bicycle.insurance_policies.build(insurance_policy_params)
    if @insurance_policy.save
      redirect_to bicycle_insurance_policies_path, notice: 'Insurance policy was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @insurance_policy = InsurancePolicy.find(params[:id])
    if @insurance_policy.update(insurance_policy_params)
      redirect_to @insurance_policy, notice: 'Insurance policy was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @insurance_policy.destroy
    # redirect_to bicycle_insurance_policies_path, notice: 'Insurance policy was successfully destroyed.'
    redirect_to request.referer || root_path
  end

  private
  def set_bicycle
    @bicycle = Bicycle.find(params[:bicycle_id])
  end

  def set_insurance_policy
    @insurance_policy = InsurancePolicy.find(params[:id])
  end

  def insurance_policy_params
    params.require(:insurance_policy).permit(:insurer, :policy_number, :description, :bicycle_id)
  end
end

app/views/insurance_policies/index.html.erb
<h1>Insurance Policies for bicycle </h1>

<ul>
  <% @insurance_policies.each do |policy| %>
    <li>
      <%= policy.insurer %>
      - Policy Number: <%= policy.policy_number %>
      Description:  <%= policy.description %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Insurance Policy', new_bicycle_insurance_policy_path %>
<%= link_to 'Back to my bicycles', bicycles_path %>

app/views/insurance_policies/new.html.erb
<h1>New Insurance Policy</h1>
<%= form_with model: [@bicycle, @insurance_policy], local: true do |form| %>
  <div>
    <%= form.label :insurer %>
    <%= form.text_field :insurer %>
  </div>
  <div>
    <%= form.label :policy_number %>
    <%= form.text_field :policy_number %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', bicycle_insurance_policies_path %>

app/views/insurance_policies/show.html.erb
<h1>Insurer: <%= @insurance_policy.insurer %></h1>
<p>Policy Number: <%= @insurance_policy.policy_number %></p>
<p>Description: <%= @insurance_policy.description %></p>

<%= link_to 'Edit', edit_bicycle_insurance_policy_path(@insurance_policy) %> |
<%= link_to 'Back', bicycle_insurance_policies_path %>