config/routes.rb
Rails.application.routes.draw do
  get 'errors/internal_server_error'
  # get 'errors/not_found'
  # get 'users_rides/new'
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  # get 'users_rides/create'
  # get 'users_rides/edit'
  # get 'users_rides/update'
  # get 'users_rides/destroy'
  devise_for :users

  # raise ActionController::RoutingError.new('Not Found')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # resources :users  # do
  #   resources :rides, only: [:create, :new, :edit, :destroy, :update]
  #  end


  resources :rides, only: [:create, :new, :edit, :destroy, :update]  do
    resources :users_rides, only: [:new]
  end

  resources :users_rides, only: [:index, :create, :edit, :update, :destroy]

  resources :components, only: [:show, :create, :new, :edit, :destroy, :update]

  resources :bicycle_components
  resources :rides, only: [:show, :index]
  # resources :warranties
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/bicycle_rack", to: "bicycles#bicycle_rack", as: :bicycle_rack
  get "/new_bicycle_code", to: "bicycles#new_code", as: :new_code
  get "/new_bicycle_validation", to: "bicycles#new_code_validation", as: :new_code_validation
  get "/my_rides", to: "rides#my_rides", as: :my_rides
  resources :rides, only: [:index]

  resources :bicycles do
    resources :components, only: [:index]
    resources :maintenances, only: [:new, :create, :index, :update]
    resources :warranties, only: [:new, :create, :index, :update]
    resources :insurance_policies, only: [:new, :create, :index, :update]
  end

    resources :maintenances, only: [:destroy]
    resources :warranties, only: [:destroy]
    resources :insurance_policies, only: [:destroy]
  root to: "pages#home"
  end

  # Defines the root path route ("/")
  # root "posts#index

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

<hr>
  <div>
    <ul class="d-flex justify-content-center list-inline footer-links">
        <li class="list-inline-item">
            <a href="#" style="font-size:14px; color:grey;">
                Privacy Policy
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#" style="font-size:14px; color:grey;">
                Terms of Service
            </a>
        </li>
        <li class="list-inline-item">
            <a href="#" style="font-size:14px; color:grey;">
                Sitemap
            </a>
        </li>
    </ul>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon container justify sticky-top style">
  <div class="container d-flex navbar-parent justify-content-between">
    <div clas="p-2 flex-shrink-1">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "logo_bike.jpg", style:"width:50px;"%>
      <% end %>
    </div>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">what is this?</span>
    </button> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <div class="main-nav-holder">
          <div class="container me-auto navbar-items">
            <ul class="navbar-nav justify-content-evenly align-items-center">
                <li class="nav-item">
                  <%= link_to "Bike Rack", bicycle_rack_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "My Rides", my_rides_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Bikes", "/bicycles", class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Club", rides_path, class: "nav-link" %>
                </li>
            </ul>
          </div>
        </div>
        <div>
          <ul class="navbar-nav m-0 p-0">
            <li class="nav-item dropdown m-0">
              <% @user = current_user %>
              <% if @user.present? %>
                <a href="#" class="avatar m-0" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <% if @user.photo.present? %>
                    <%= cl_image_tag @user.photo.key, class: "avatar biker", alt: "Profile Picture", style:"border-radius:50%; width:50px;"%>
                  <% else %>
                    <%= image_tag "biker.png", class: "avatar biker", alt: "Default Profile Picture", style: "width:50px;" %>
                  <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
                </div>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <%# <div class="container d-flex justify-content-evenly" style="border:2px solid blue"> %>
          <div class="main-nav-holder w-100 sm-col-3">
            <div class="navbar-items">
              <ul class="navbar-nav justify-content-center">
                  <li class="nav-item">
                    <%= link_to "Bike Rack", bicycle_rack_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "My Rides", my_rides_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Club", rides_path, class: "nav-link" %>
                  </li>
              </ul>
            </div>
          </div>
          <div class="mt-1">
            <button id="saddle_btn" class="nav-item active">
              <%= link_to "Saddle Up!", new_user_session_path %>
            </button>
          </div>
        <%# </div> %>
      <% end %>
    </div>
  </div>
</div>