config/routes.rb
Rails.application.routes.draw do
  get 'errors/internal_server_error'
  # get 'errors/not_found'
  # get 'users_rides/new'
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  # get 'users_rides/create'
  # get 'users_rides/edit'
  # get 'users_rides/update'
  # get 'users_rides/destroy'
  devise_for :users

  # raise ActionController::RoutingError.new('Not Found')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # resources :users  # do
  #   resources :rides, only: [:create, :new, :edit, :destroy, :update]
  #  end


  resources :rides, only: [:create, :new, :edit, :destroy, :update]  do
    resources :users_rides, only: [:new]
  end

  resources :users_rides, only: [:index, :create, :edit, :update, :destroy]

  resources :components, only: [:show, :create, :new, :edit, :destroy, :update]

  resources :bicycle_components
  resources :rides, only: [:show, :index]
  # resources :warranties
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/bicycle_rack", to: "bicycles#bicycle_rack", as: :bicycle_rack
  get "/new_bicycle_code", to: "bicycles#new_code", as: :new_code
  get "/new_bicycle_validation", to: "bicycles#new_code_validation", as: :new_code_validation
  get "/my_rides", to: "rides#my_rides", as: :my_rides
  resources :rides, only: [:index]

  resources :bicycles do
    resources :components, only: [:index]
    resources :maintenances, only: [:new, :create, :index, :update]
    resources :warranties, only: [:new, :create, :index, :update]
    resources :insurance_policies, only: [:new, :create, :index, :update]
  end

    resources :maintenances, only: [:destroy]
    resources :warranties, only: [:destroy]
    resources :insurance_policies, only: [:destroy]
  root to: "pages#home"
  end

  # Defines the root path route ("/")
  # root "posts#index

app/views/pages/_landing_page.html.erb
</div>
<div class="background_image">
   <div class="container">
    <div class="row justify-content-center">
      <div id="open_message" class="col-md-12 text-center bg-light">
        <h1 class="display-6 fw-bold mt-3">"Your Bike's Perfect Haven."</h1>
        <h3 class="lead mt-5">For every adventure you chase and every dream you live, your bike deserves a safe home. With us, you ride free, knowing we’ve got your back—always and everywhere.</h3>
      </div>
    </div>
  </div>
</div>


<footer>
  <footer class="footer py-5 bg-secondary text-light">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-md-3">
                    <h5>About Us</h5>
                    <p id="about">
                      "Your Bike's Trusted Companion for Every Ride."
                      At Bicycle Passport, we understand the importance of your bicycle—it's more than just a mode of
                      transportation; it’s a partner in your adventures. With us, your bike’s legacy is safe, organized,
                      and ready for every ride.
                    </p>
                </div>
                <div class="col-md-3">
                    <h5>Contact Us</h5>
                    <ul class="list-unstyled">
                        <li>Email: partytime@example.com</li>
                        <li>Phone: +351 925665532</li>
                        <li>Address: party all the time Street, Lisbon, Portugal</li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Follow Us</h5>
                    <ul class="list-inline footer-links">
                        <li class="list-inline-item">
                          <a href="#">
                                <i class="fab fa-facebook list-inline-item"></i>
                          </a>
                          </li>
                        <li class="list-inline-item list-inline-item">
                          <a href="#">
                                <i class="fab fa-x list-inline-item"></i>
                          </a>
                        </li>
                        <li class="list-inline-item ">
                          <a href="#">
                                <i class="fab fa-instagram list-inline-item"></i>
                          </a>
                        </li>
                        <li class="list-inline-item">
                          <a href="#">
                                <i class="fab fa-linkedin list-inline-item"></i>
                          </a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2024 Your Website. All rights reserved.</p>
                </div>
                <div class="col-md-6 text-end">
                    <ul class="list-inline footer-links">
                        <li class="list-inline-item">
                            <a href="#" class="text-black">
                                Privacy Policy
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-black">
                                Terms of Service
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="text-black">
                                Sitemap
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</footer>

app/views/pages/_userhome.html.erb
    <div class="img-header-holder d-flex justify-content-center">
     <% if @bicycle.photo.present? %>
      <%= cl_image_tag @bicycle.photo.key, alt: "Bike image", class: "rounded", height:850, crop: :fill %>
    <% else %>
      <%= image_tag "Giant.jpg", alt: "Bike image", class: "rounded", height:850, crop: :fill %>
    <% end %>
    </div>


    <div class="edges d-flex justify-content-between m-0">
      <div class="d-flex flex-column align-items-start">
        <div>
          <h1><%= @bicycle.name %></h1>
          <h3><strong><%=@bicycle.make  %></strong>
          <a href="#details"><i class="fa-solid fa-circle-info" style="font-size: 24px"></i></a>
          <a href="#rides"><i class="fa-solid fa-bicycle" style="font-size: 24x"></i></a>
          <a href="#log_book"><i class="fa-solid fa-book" style="font-size: 24px"></i></a>
            <% if @bicycle.verified %>
              <%= image_tag "certified-icon.png", alt: "icon", style: "width:50px; heigth:50px;" %>
            <% end %>
          </h3>
        </div>


      </div>

      <div class="d-flex flex align-items-center">

      <div>
      <% if current_user == @bicycle.user %>
        <%= link_to "Edit", edit_bicycle_path(@bicycle), class: "btn button"%>
        <% end %>
      </div>

      <div>
      <% if current_user == @bicycle.user %>
      <button class="px-3" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
         Share <i class="fa-solid fa-share-nodes"></i>
      </button>
      <% end %>


<!-- Modal -->
          <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Your unique code:</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <%= @unique_code  %>
                </div>
                <div class="modal-footer">
                  <%# <span data-bs-dismiss="modal" id="clipboard">Copy</span> %>
                  <%# <span> / </span> %>
                  <%# <h6>Copy</h6> %>
                </div>
              </div>
            </div>
          </div>


      </div>



      </div>

    </div>



    <div>
      <p><strong><%=@bicycle.description  %></strong></p>
          <% if @warranty %>
          <p>Current Warranty: <%= @warranty.issuer %></p>
          <% end %>
          <% if @insurance %>
          <p>Current Insurance policy: <%= @insurance.insurer%> - <%= @insurance.policy_number%></p>
          <% end %>
    </div>
<hr>

<div id="details">
  <div class="d-flex justify-content-between edges mb-4">
  <h3>Details</h3>
    <div>
        <%= link_to "See all", "/bicycles/#{@bicycle.id}/components", class: "btn btn-confirm" %>
    </div>
  </div>

  <div class="cards d-flex justify-content-between">

  <% @featured_components.each do |component| %>
      <div class="card d-flex justify-content-center" style="height:400px; width:285px;">
        <div class="mb-auto">
          <% if component.photo.present? %>
          <%= cl_image_tag component.photo.key, alt: component.name, class: "rounded", style: "width:283px;", crop: :fill %>
          <% else %>
          <%= image_tag "carbon-wheel.jpg", alt: "wheel", class: "rounded", style: "width:280px;", crop: :fill %>
          <% end %>
        </div>
        <div class="card-body d-flex flex-column align-items-center">
      <h5 class="card-title text-center mt-auto"><%= link_to component.name, component_path(component), class:'stretched-link' %></h5>
      <p class="card-text text-center"><%= component.make %></p>
    </div>
      </div>

<% end %>


  </div>

</div>
<hr>
<% if @bicycle.user == current_user %>
<div id="rides">
  <div class="head d-flex justify-content-between edges mb-3">
    <h3>Rides</h3>
    <div>
      <%= link_to "See full history", "/rides", class: "btn btn-confirm" %>
    </div>
  </div>
  <div class="d-flex">

      <%# <%= image_tag "illustration.jpg", alt: "wheel", class: "rounded", style: "width:550px;" %>
      <div class="map-container mt-0" style="width: 100%; height: 482px; max-width:520px; margin-top:40px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%=ENV['MAPBOX_API_KEY']%>">
      </div>
      <div class="right">
        <div class="body-list">

        <% @featured_rides.each do |ride| %>
          <div class="card ride-card">
            <div class="card-body d-flex justify-content-between">

              <div class="first-line col-5 text-start m-0">
                <h6 class="event-name"><%= ride.name %></h6>
                <p class="event-date m-0"> <%= link_to ride.start_date, ride_path(ride), class:'stretched-link' %></p>
              </div>
              <div class="second-line col-6 text-end d-flex flex justify-content-between align-items-center">
              <% results_start = Geocoder.search([ ride.start_lat, ride.start_long]) %>
              <% results_end = Geocoder.search([ ride.end_lat, ride.end_long]) %>
                <span class="route">From <%= results_start.first.city %> to  <%= results_end.first.city %> </span>
                <span class="route-length"><%= ride.distance %> KM</span>
              </div>
            </div>
          </div>
        <% end %>

        </div>
      </div>
  </div>
</div>
<% end %>


<hr>
<div class="mb-5" id="log_book">
  <div class="d-flex justify-content-between edges mb-3">

      <h3>Log Book</h3>
      <div>
        <%= link_to "See full history", bicycle_maintenances_path(@bicycle), class: "btn btn-default" %>
      </div>

  </div>
    <div class="d-flex flex-column justify-content-evenly">
      <div>
        <% @featured_maintenances.each do |maintenance| %>
          <div class="card ps-0 pe-0">
            <div class=" card-body">
              <div class="second-line d-flex justify-content-between">
                <span class="maintenance col-4 text-start"><%= maintenance.description %>
                  <% if @bicycle.verified %>
                  <span><ion-icon name="checkmark-circle-outline"></ion-icon></span>
                  <% end %>
                </span>
                <span class="shop-name col-4 text-center"><%= maintenance.shop %> </span>
                <span class="route col-4 text-end"><%= maintenance.date %> </span>
              </div>
            </div>
          </div>
          <% end %>
      </div>
    </div>

</div>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

app/views/pages/home.html.erb
<div class="container">
  <% if user_signed_in? %>

    <%= render "userhome" %>

    <%= render "shared/footer" %>
    
   <% else %>

      <%= render "landing_page" %>

  <% end %>
</div>