config/routes.rb
Rails.application.routes.draw do
  get 'errors/internal_server_error'
  # get 'errors/not_found'
  # get 'users_rides/new'
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'
  # get 'users_rides/create'
  # get 'users_rides/edit'
  # get 'users_rides/update'
  # get 'users_rides/destroy'
  devise_for :users

  # raise ActionController::RoutingError.new('Not Found')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # resources :users  # do
  #   resources :rides, only: [:create, :new, :edit, :destroy, :update]
  #  end


  resources :rides, only: [:create, :new, :edit, :destroy, :update]  do
    resources :users_rides, only: [:new]
  end

  resources :users_rides, only: [:index, :create, :edit, :update, :destroy]

  resources :components, only: [:show, :create, :new, :edit, :destroy, :update]

  resources :bicycle_components
  resources :rides, only: [:show, :index]
  # resources :warranties
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/bicycle_rack", to: "bicycles#bicycle_rack", as: :bicycle_rack
  get "/new_bicycle_code", to: "bicycles#new_code", as: :new_code
  get "/new_bicycle_validation", to: "bicycles#new_code_validation", as: :new_code_validation
  get "/my_rides", to: "rides#my_rides", as: :my_rides
  resources :rides, only: [:index]

  resources :bicycles do
    resources :components, only: [:index]
    resources :maintenances, only: [:new, :create, :index, :update]
    resources :warranties, only: [:new, :create, :index, :update]
    resources :insurance_policies, only: [:new, :create, :index, :update]
  end

    resources :maintenances, only: [:destroy]
    resources :warranties, only: [:destroy]
    resources :insurance_policies, only: [:destroy]
  root to: "pages#home"
  end

  # Defines the root path route ("/")
  # root "posts#index

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :users, through: :users_ride
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
    @rides = Ride.all
    @user = current_user
    @users = User.all
  end

  def show
    @ride = Ride.find(params[:id])
    @user = current_user
    @users_rides_this_ride = UsersRide.where(ride_id: @ride )
    @ids_of_participants = [];
    @bikes_of_participants = [];
    @users_rides_this_ride.map do |participant|
      if !@ids_of_participants.include?(participant.user_id)
        @ids_of_participants << participant.user_id
        @bikes_of_participants << participant.bicycle
      end

    end

    @user_was_on_ride = @ids_of_participants.include?(@user.id)
    # @users_on_ride = User.all.select {|user| user.id == current_user}
    # @users_on_ride = User.all.reject{ |user| user.id == current_user.id}


    @markers = [ {
      lat: @ride.start_lat,
      lng: @ride.start_long
    },{
      lat: @ride.end_lat,
      lng: @ride.end_long
    }]

  end

  def new
    @ride = Ride.new
    @user = current_user
  end

  def edit
    @ride = Ride.find(params[:id])
  end

  def update
    @ride = Ride.find(params[:id])
    @ride.update(ride_params_from_form)
    redirect_to ride_path(@ride)
  end

  def create
    @ride = Ride.new(ride_params_from_form)
    @user = current_user
    @ride.user = current_user
    @ride.save
    redirect_to my_rides_path
 end

  def destroy
    @ride = Ride.find(params[:id])
    @ride.destroy
    redirect_to rides_path, status: :see_other
  end

  def my_rides
    @rides = Ride.select {|ride| ride.user == current_user}
    @user = current_user
  end

  private

  def ride_params
    params.require(:ride).permit(:name, :start_lat, :start_long, :end_lat, :end_long, :start_date, :start_time, :end_time, :end_date, :distance, :user, :photo)
  end

  def ride_params_from_form
    result_start = Geocoder.search(params[:ride][:start_lat])
    result_end = Geocoder.search(params[:ride][:end_lat])

    params[:ride][:start_lat] = result_start.first.coordinates[0].to_f
    params[:ride][:start_long] = result_start.first.coordinates[1].to_f
    params[:ride][:end_lat] = result_end.first.coordinates[0].to_f
    params[:ride][:end_long] = result_end.first.coordinates[1].to_f

    ride_params
   # params.require(:ride).permit(:name, :start_lat, :start_long, :end_lat, :end_long, :start_date, :start_time, :end_time, :end_date, :distance, :user)
  end
end

app/views/rides/_form.html.erb
<%= simple_form_for [@ride] do |f| %>

  <%=  f.input :name, as: :string %>
  <%=  f.input :start_lat, label: 'Starting Location', as: :string %>
  <%=  f.input :end_lat, label: 'Ending Location', as: :string %>
  <%=  f.input :start_date, as: :date  %>
  <%=  f.input :start_time, as: :time  %>
  <%=  f.input :end_date, as: :date  %>
  <%=  f.input :end_time, as: :time  %>
  <%=  f.input :distance, as: :integer  %>
  <%=  f.input :photo, as: :file  %>
  <button>
    <%= f.submit "Submit Ride", style:"background-color:#899687; border:none" %>
  </button>
<% end %>

<%# data: { controller: "ride-creation", action: 'submit->ride-creation#grabCreation' } %>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

app/views/rides/_index.html.erb
<div class="container grid card-container bg-white" id="card-container">

  <div class="d-flex p-0 mt-5 col-4 justify-content-between">
  <%= link_to root_path do %>
  <span>  <ion-icon name="arrow-undo-outline"></ion-icon>  Back </span>
  <% end %>
  </div>

<%# <div class="container grid card-container bg-white mt-5" id="card-container"> %>
<h1 class="d-flex justify-content-center"> Popular Rides </h1>
<div class="row">

<% if !@rides.nil? && @rides.count > 0 %>
  <% @rides.each do |ride| %>
    <div class="card col-sm-4 bike-card p-0 mt-5">
    <div class="m-3 card-holder text-wrap" style="height:450px;">
      <%# <img src="..." class="card-img-top" alt="Your bike here"> %>
      <% if ride.photo.present? %>
        <div class="m-3 d-flex align-content-center justify-content-center">
        <%= cl_image_tag ride.photo.key, height: 250, width: 350, crop: :fill %>
        </div>
      <% end %>

      <div class="card-body">
        <h5 class="card-title"> <%= link_to ride.name, ride_path(ride), class:'stretched-link' %></h5>

        <% results_start = Geocoder.search([ ride.start_lat, ride.start_long]) %>
        <% results_end = Geocoder.search([ ride.end_lat, ride.end_long]) %>
        <p class="card-text"><%= results_start.first.city %> to <%= results_end.first.city %> </p>

        <p class="card-text"> <%= ride.distance %> km <p>

      </div>
    </div>
    </div>
  <% end %>
  <% end %>



      <div class="d-flex justify-content-center p-0 mt-2">
        <%# <button class="me-3">
          <%= link_to "Back", bicycle_path(@user) %>
        <%# </button> %>
        <button>

          <%= link_to "Add a new ride", new_ride_path %>

        </button>

      </div>
  </div>

<%# </div> %>
</div>

app/views/rides/create.html.erb
<h1>Rides#create</h1>
<p>Find me in app/views/rides/create.html.erb</p>

app/views/rides/destroy.html.erb
<h1>Rides#destroy</h1>
<p>Find me in app/views/rides/destroy.html.erb</p>

app/views/rides/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="jumbotron" style="width:900px; padding: 20px;">
    <h1 class="display-5 d-flex justify-content-center">Edit Ride</h2>
    <hr class="my-4">
    <%= link_to bicycle_rack_path do %>
      <span>  <ion-icon name="arrow-undo-outline"></ion-icon>  Back </span>
    <% end %>
    <div class="d-flex flex-column align-items-center">
    <%= render "form", ride: @ride %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/rides/index.html.erb
<%# <h1 class="d-flex justify-content-center"> Popular Rides </h1> %>

<%= render "index" %>

<%= render "shared/footer" %>

app/views/rides/my_rides.html.erb
<div class="container grid card-container bg-white mt-5 mb-3" id="card-container">
  <div class="d-flex p-0 mt-5 col-4 justify-content-between">
    <%= link_to root_path do %>
      <span>  <ion-icon name="arrow-undo-outline"></ion-icon>  Back </span>
    <% end %>
  </div>

  <h1 class="d-flex justify-content-center"> Your Rides </h1>
  <div class="row">

  <% if !@rides.nil? && @rides.count > 0 %>
    <% @rides.each do |ride| %>
      <div class="card col-sm-4 bike-card p-0 mt-5">
      <div class="m-3 card-holder text-wrap" style="height:450px;">
        <%# <img src="..." class="card-img-top" alt="Your bike here"> %>
        <% if ride.photo.present? %>
        <div class="m-3 d-flex align-content-center justify-content-center">
        <%= cl_image_tag ride.photo.key, height: 250, width: 350, crop: :fill %>
        </div>
        <% end %>
        <div class="card-body" id="wraper">
          <h5 class="card-title"> <%= link_to ride.name, ride_path(ride), class:'stretched-link' %></h5>
          <% results_start = Geocoder.search([ ride.start_lat, ride.start_long]) %>
          <% results_end = Geocoder.search([ ride.end_lat, ride.end_long]) %>
          <p class="card-text"><%= results_start.first.city %> to <%= results_end.first.city %> </p>
          <p class="card-text"> <%= ride.distance %> km<p>
        </div>
      </div>
      </div>
    <% end %>
    <% end %>
      <div class="d-flex justify-content-center p-0 mt-2">
        <button class="px-2">
          <%= link_to "Add a new ride", new_ride_path(@user) %>
        </button>
      </div>
    </div>
</div>

<%= render "shared/footer" %>

app/views/rides/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="jumbotron" style="width:900px; padding: 20px;">
    <h1 class="display-5 d-flex justify-content-center">New ride</h2>
    <hr class="my-4">
      <%= link_to bicycle_rack_path do %>
      <span><ion-icon name="arrow-undo-outline"></ion-icon>  Back </span>
      <% end %>
    <div class="d-flex flex-column align-items-center">
      <%= render "form", ride: @ride, user: @user %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/rides/show.html.erb
<div class="container flex-wrap mb-5 justify-content-center">

  <div class="d-flex p-0 mt-5 col-4 justify-content-between">
      <%= link_to rides_path do %>
      <span>  <ion-icon name="arrow-undo-outline"></ion-icon>  Back </span>
      <% end %>
  </div>

  <div class="text-container text-center my-3">

    <h1><%= @ride.name %></h1>
    <% results_start = Geocoder.search([ @ride.start_lat, @ride.start_long]) %>
    <% results_end = Geocoder.search([ @ride.end_lat, @ride.end_long]) %>
    <h3> <%= results_start.first.city %> to <%= results_end.first.city %></h3>
    <p> Started: <%= @ride.start_date %> @ <%= @ride.start_time.strftime('%H:%M')  %></p>
    <p> Finished: <%= @ride.end_date %> @ <%= @ride.end_time.strftime('%H:%M') %></p>
    <p> <%= @ride.distance %> Km </p>
    <%# <%= link_to  new_ride_users_ride_path(@ride) do %>
        <%# <span> <i class="fa-solid fa-bicycle"></i> I was there! </span> %>
      <%# <% end %>
  </div>

  <div class="d-flex justify-content-center">
      <div class="map-container align-self-center" style="width: 100%; height: 300px; max-width:900px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%=ENV['MAPBOX_API_KEY']%>">
      </div>
  </div>


 <div class="text-container text-start-middle px-3 my-3 col-5" style="margin-left:195px">

    <h4>Who was there?</h4>

    <%if @user_was_on_ride  %>

      <p>You were on this event on <%= @ride.start_date %>. Not correct? Remove yourself <%= link_to  new_ride_users_ride_path(@ride) do %>
                  <span> here </span>
                <% end %></p>
      <% else %>

        <p> Were you there? .....Mention it <%= link_to  new_ride_users_ride_path(@ride) do %>
                  <span> here </span>
                <% end %>
    <% end %>

    <% @ids_of_participants.each_with_index do |id, index| %>
        <% part = User.find(id) %>
        <% bike = @bikes_of_participants[index] %>
        <% if part.photo.present? %>
        <div class="d-flex justify-content-start align-items-center">
        <%= cl_image_tag part.photo.key, style:"width: 50px", class: "rounded-circle" %>
        <h4 class="p-3"> <%= User.find(id).name %>
        <%= link_to bicycle_path(bike) do %>
         <i class="fa-solid fa-bicycle" style="font-size: 24x"></i></h4>

        <% end %>

        </div>
       <% end %>
    <% end %>

  </div>
  <div class="text-center mt-2">
    <% if current_user == @ride.user %>
    <button class="px-2">
      <%= link_to "Edit Ride",  edit_ride_path(@ride) %>
    </button>
      <% end %>
  </div>

</div>

<%= render "shared/footer" %>